version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: demo_postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432" 